### PR TITLE
Create Client-HideChatCommands.lua

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by watameln** [comment]
This plugin creates a false positive in the anticheat

**Comment by ccuser44** [comment]
> This plugin creates a false positive in the anticheat

Whats the message?

**Comment by watameln** [comment]
Adonis_10042

**Comment by Dimenpsyonal** [comment]
1 year later and still draft 🥱 🥱

**Comment by ccuser44** [comment]
Closed in favour of #34

**Pull request closed without merging**
