### PR TITLE
Create f3x_override.lua

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by ccuser44** [comment]
I'm not sure if I should use CC0 or Unlicense. CC0 is longer but Unlicense is not as good law wise in every country

**Comment by LiveFireExercise** [comment]
No CC for code.

**Comment by ccuser44** [comment]
> No CC for code.

Do I use Unlicense then? And CC0 can be used for code FSF and CC later endorsed it for code

**Comment by LiveFireExercise** [comment]
L

**Comment by Dimenpsyonal** [comment]
This plugin is 5 lines of code yet the file is 141 lines

**Comment by ccuser44** [comment]
> This plugin is 5 lines of code yet the file is 141 lines

Yes

**Comment by Dimenpsyonal** [comment]
this is why ccuser44 should never be trusted fr

**Comment by ccuser44** [comment]
> this is why ccuser44 should never be trusted fr

Better trust being too careful with law than being careless

**Comment by Dimenpsyonal** [comment]
what

**Pull request merged**
