### PR TITLE
Chat Ban Notifications Release

### PR DESCRIPTION
**Pull request by watameln**
My tag is watameln#7484
and rblx username is lbe07 idk if i can get contributor role from this?

### CODE REVIEW

**Comment by watameln** [comment]
I don't know if i can get a contributor role/rank from this but if I could that would be great.

**Comment by watameln** [comment]
And what it does is put "PLAYER was AAC (Adonis anticheat - kinda like in arsenal if yk what i mean) banned" when a player was banned.

**Comment by coasterteam** [comment]
Should add some setting to let game owners toggle it, as sometimes they may not want to publicly announce that stuff to all players, or even just set who gets the notifications. Like a minimum admin level.

**Comment by fxeP1** [comment]
You should probably remove the debug traces of prints inside.

P.S: You've defined Remote as a variable but haven't used it.

**Review by LawMixer — CHANGES_REQUESTED** [review]
Probably should remove debugging lines, and it looks good to me. Just @ me here and I will review it once you made those changes.

**Pull request closed without merging**
